import { TUTORIAL_ANCHORS } from "./anchors";
import { FLASH_POINT_CONCEPT_MODEL } from "./flashPointConcept";
import {
  assaultFlashKilled,
  coreFurnaceFeedEnabled,
  furnaceAgitatorRunning,
  primeFlashIncident,
  roomHasAgitator,
  roundResolved,
} from "./flashPointGuideState";
import type { GuideDefinition } from "./guideModel";

export const firstSparkGuide: GuideDefinition = {
  completion: {
    title: "tutorial.flash.firstSpark.completion.title",
    explanation: "tutorial.flash.firstSpark.completion.explanation",
    instruction: "tutorial.flash.firstSpark.completion.instruction",
  },
  id: "flash_point:first_spark:v5",
  dismissalId: "flash_point:field_guidance:v5",
  label: "tutorial.flash.firstSpark.label",
  showStageIntro: true,
  gatesPhaseActions: true,
  firstFlashTeachingBreak: true,
  story: {
    kicker: "tutorial.flash.firstSpark.story.kicker",
    title: "tutorial.flash.firstSpark.story.title",
    paragraphs: ["tutorial.flash.firstSpark.story.paragraph.0"],
    model: FLASH_POINT_CONCEPT_MODEL,
  },
  mission: {
    title: "tutorial.flash.firstSpark.mission.title",
    summary: "tutorial.flash.firstSpark.mission.summary",
    tasks: [
      {
        id: "mix-chamber",
        label: "tutorial.flash.firstSpark.task.mixChamber",
        completed: (game) => roomHasAgitator(game, "furnace") && furnaceAgitatorRunning(game),
      },
      {
        id: "feed-reactants",
        label: "tutorial.flash.firstSpark.task.feedReactants",
        completed: coreFurnaceFeedEnabled,
      },
      {
        id: "prove-ignition",
        label: "tutorial.flash.firstSpark.task.proveIgnition",
        completed: (game) => Boolean(primeFlashIncident(game)),
      },
      {
        id: "catch-deckmouth",
        label: "tutorial.flash.firstSpark.task.catchDeckmouth",
        completed: assaultFlashKilled,
      },
    ],
  },
  steps: [
    {
      id: "install-agitator",
      kind: "action",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.furnaceAgitator,
      title: "tutorial.flash.firstSpark.step.installAgitator.title",
      explanation: "tutorial.flash.firstSpark.step.installAgitator.explanation",
      instruction: "tutorial.flash.firstSpark.step.installAgitator.instruction",
      result: "tutorial.flash.firstSpark.step.installAgitator.result",
      completed: (game) => roomHasAgitator(game, "furnace"),
    },
    {
      id: "run-agitator",
      kind: "action",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.furnaceAgitatorToggle,
      title: "tutorial.flash.firstSpark.step.runAgitator.title",
      explanation: "tutorial.flash.firstSpark.step.runAgitator.explanation",
      instruction: "tutorial.flash.firstSpark.step.runAgitator.instruction",
      result: "tutorial.flash.firstSpark.step.runAgitator.result",
      completed: furnaceAgitatorRunning,
    },
    {
      id: "open-pipe-board",
      kind: "action",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.pipeModeToggle,
      title: "tutorial.flash.firstSpark.step.openPipeBoard.title",
      explanation: "tutorial.flash.firstSpark.step.openPipeBoard.explanation",
      instruction: "tutorial.flash.firstSpark.step.openPipeBoard.instruction",
      result: "tutorial.flash.firstSpark.step.openPipeBoard.result",
      completed: (game, ui) => ui.pipeMode || coreFurnaceFeedEnabled(game),
    },
    {
      id: "start-shared-duct",
      kind: "action",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.conduitCoreFurnaceGas,
      title: "tutorial.flash.firstSpark.step.startSharedDuct.title",
      explanation: "tutorial.flash.firstSpark.step.startSharedDuct.explanation",
      instruction: "tutorial.flash.firstSpark.step.startSharedDuct.instruction",
      result: "tutorial.flash.firstSpark.step.startSharedDuct.result",
      completed: coreFurnaceFeedEnabled,
    },
    {
      id: "begin-prime",
      kind: "action",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.beginPrime,
      title: "tutorial.flash.firstSpark.step.beginPrime.title",
      explanation: "tutorial.flash.firstSpark.step.beginPrime.explanation",
      instruction: "tutorial.flash.firstSpark.step.beginPrime.instruction",
      result: "tutorial.flash.firstSpark.step.beginPrime.result",
      completed: (game) => game.phase !== "build",
    },
    {
      id: "accelerate-clock",
      kind: "action",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.simulationSpeed,
      title: "tutorial.flash.firstSpark.step.accelerateClock.title",
      explanation: "tutorial.flash.firstSpark.step.accelerateClock.explanation",
      instruction: "tutorial.flash.firstSpark.step.accelerateClock.instruction",
      result: "tutorial.flash.firstSpark.step.accelerateClock.result",
      completed: (game) => game.speed === 2,
    },
    {
      id: "observe-prime-flash",
      kind: "observe",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.furnaceIncidents,
      title: "tutorial.flash.firstSpark.step.observePrimeFlash.title",
      explanation: "tutorial.flash.firstSpark.step.observePrimeFlash.explanation",
      instruction: "tutorial.flash.firstSpark.step.observePrimeFlash.instruction",
      result: "tutorial.flash.firstSpark.step.observePrimeFlash.result",
      completed: (game) => Boolean(primeFlashIncident(game)),
    },
    {
      id: "cold-assault",
      kind: "observe",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.phaseBanner,
      title: "tutorial.flash.firstSpark.step.coldAssault.title",
      explanation: "tutorial.flash.firstSpark.step.coldAssault.explanation",
      instruction: "tutorial.flash.firstSpark.step.coldAssault.instruction",
      result: "tutorial.flash.firstSpark.step.coldAssault.result",
      completed: (game) => game.phase !== "assault" || Boolean(primeFlashIncident(game)),
    },
    {
      id: "start-assault",
      kind: "action",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.startAssault,
      title: "tutorial.flash.firstSpark.step.startAssault.title",
      explanation: "tutorial.flash.firstSpark.step.startAssault.explanation",
      instruction: "tutorial.flash.firstSpark.step.startAssault.instruction",
      result: "tutorial.flash.firstSpark.step.startAssault.result",
      completed: (game) => game.phase === "assault" || game.phase === "round_result",
    },
    {
      id: "observe-combat-flash",
      kind: "observe",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.furnaceIncidents,
      title: "tutorial.flash.firstSpark.step.observeCombatFlash.title",
      explanation: "tutorial.flash.firstSpark.step.observeCombatFlash.explanation",
      instruction: "tutorial.flash.firstSpark.step.observeCombatFlash.instruction",
      result: "tutorial.flash.firstSpark.step.observeCombatFlash.result",
      completed: assaultFlashKilled,
    },
  ],
};

export const storedMomentumGuide: GuideDefinition = {
  completion: {
    title: "tutorial.flash.storedMomentum.completion.title",
    explanation: "tutorial.flash.storedMomentum.completion.explanation",
    instruction: "tutorial.flash.storedMomentum.completion.instruction",
  },
  id: "flash_point:stored_momentum:v1",
  dismissalId: "flash_point:field_guidance:v5",
  label: "tutorial.flash.storedMomentum.label",
  showStageIntro: false,
  gatesPhaseActions: false,
  firstFlashTeachingBreak: false,
  story: {
    kicker: "tutorial.flash.storedMomentum.story.kicker",
    title: "tutorial.flash.storedMomentum.story.title",
    paragraphs: [
      "tutorial.flash.storedMomentum.story.paragraph.0",
      "tutorial.flash.storedMomentum.story.paragraph.1",
    ],
    model: null,
  },
  mission: {
    title: "tutorial.flash.storedMomentum.mission.title",
    summary: "tutorial.flash.storedMomentum.mission.summary",
    tasks: [
      {
        id: "confirm-cycle",
        label: "tutorial.flash.storedMomentum.task.confirmCycle",
        completed: (game) => furnaceAgitatorRunning(game) && coreFurnaceFeedEnabled(game),
      },
      {
        id: "start-short-prime",
        label: "tutorial.flash.storedMomentum.task.startShortPrime",
        completed: (game) => game.phase !== "build",
      },
      {
        id: "read-short-prime",
        label: "tutorial.flash.storedMomentum.task.readShortPrime",
        completed: (game) => game.phase !== "build" && game.phase !== "prime",
      },
      {
        id: "hold-followup",
        label: "tutorial.flash.storedMomentum.task.holdFollowup",
        completed: roundResolved,
      },
    ],
  },
  steps: [
    {
      id: "prepare-followup",
      kind: "action",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.beginPrime,
      title: "tutorial.flash.storedMomentum.step.prepareFollowup.title",
      explanation: "tutorial.flash.storedMomentum.step.prepareFollowup.explanation",
      instruction: "tutorial.flash.storedMomentum.step.prepareFollowup.instruction",
      result: "tutorial.flash.storedMomentum.step.prepareFollowup.result",
      completed: (game) => game.phase !== "build",
    },
    {
      id: "observe-followup-prime",
      kind: "observe",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.furnaceIncidents,
      title: "tutorial.flash.storedMomentum.step.observeFollowupPrime.title",
      explanation: "tutorial.flash.storedMomentum.step.observeFollowupPrime.explanation",
      instruction: "tutorial.flash.storedMomentum.step.observeFollowupPrime.instruction",
      result: "tutorial.flash.storedMomentum.step.observeFollowupPrime.result",
      completed: (game) => game.phase !== "build" && game.phase !== "prime",
    },
    {
      id: "observe-followup-assault",
      kind: "observe",
      roomId: "furnace",
      target: TUTORIAL_ANCHORS.phaseBanner,
      title: "tutorial.flash.storedMomentum.step.observeFollowupAssault.title",
      explanation: "tutorial.flash.storedMomentum.step.observeFollowupAssault.explanation",
      instruction: "tutorial.flash.storedMomentum.step.observeFollowupAssault.instruction",
      result: "tutorial.flash.storedMomentum.step.observeFollowupAssault.result",
      completed: roundResolved,
    },
  ],
};
