import type { DeviceDefinition, DeviceKey, RoomId } from "../types";

export const DEVICE_CATALOG: Record<DeviceKey, DeviceDefinition> = {
  gas_toxic: {
    key: "gas_toxic",
    kind: "gas_tank",
    name: "Toxic gas bank",
    family: "Tank · duct · valve",
    description: "Injects a concentrated toxic charge, displacing the current atmosphere.",
    activeLabel: "Inject toxic",
    cost: 1,
    energyCost: 18,
    cooldown: 6,
    accent: "#b4dc45",
    gasPayload: "toxic_gas",
  },
  gas_co2: {
    key: "gas_co2",
    kind: "gas_tank",
    name: "CO₂ pressure tank",
    family: "Tank · duct · valve",
    description: "Displaces oxygen and suppresses combustion in the target chamber.",
    activeLabel: "Flood CO₂",
    cost: 1,
    energyCost: 16,
    cooldown: 5,
    accent: "#8e9b98",
    gasPayload: "co2",
  },
  gas_fuel: {
    key: "gas_fuel",
    kind: "gas_tank",
    name: "Fuel gas bank",
    family: "Tank · duct · valve",
    description: "Adds combustible gas. It remains harmless until oxygen and ignition meet.",
    activeLabel: "Inject fuel",
    cost: 1,
    energyCost: 17,
    cooldown: 6,
    accent: "#efa24f",
    gasPayload: "fuel_gas",
  },
  liquid_acid: {
    key: "liquid_acid",
    kind: "liquid_tank",
    name: "Acid dump tank",
    family: "Tank · pipe · pump",
    description: "Dumps a deep acid charge that is strongest before dilution.",
    activeLabel: "Dump acid",
    cost: 1,
    energyCost: 20,
    cooldown: 8,
    accent: "#d7e53d",
    liquidPayload: "acid",
  },
  liquid_caustic: {
    key: "liquid_caustic",
    kind: "liquid_tank",
    name: "Caustic dump tank",
    family: "Tank · pipe · pump",
    description: "Damages organics but neutralizes any acid already in the room.",
    activeLabel: "Dump caustic",
    cost: 1,
    energyCost: 20,
    cooldown: 8,
    accent: "#b06ddd",
    liquidPayload: "caustic",
  },
  liquid_water: {
    key: "liquid_water",
    kind: "liquid_tank",
    name: "Water header",
    family: "Tank · pipe · pump",
    description: "Adds water for boiling and flushing, but dilutes acids, caustics, and sludge.",
    activeLabel: "Pump water",
    cost: 1,
    energyCost: 12,
    cooldown: 5,
    accent: "#4ca9d6",
    liquidPayload: "water",
  },
  liquid_sludge: {
    key: "liquid_sludge",
    kind: "liquid_tank",
    name: "Sludge hopper",
    family: "Tank · pipe · pump",
    description: "Lays a persistent slowing pool for ground enemies.",
    activeLabel: "Drop sludge",
    cost: 1,
    energyCost: 16,
    cooldown: 7,
    accent: "#98774a",
    liquidPayload: "sludge",
  },
  vent: {
    key: "vent",
    kind: "vent",
    name: "Atmospheric vent",
    family: "Vent · filter",
    description: "Expels most room gas and replaces it with breathable ambient air.",
    activeLabel: "Flush atmosphere",
    cost: 1,
    energyCost: 14,
    cooldown: 7,
    accent: "#82b9c5",
  },
  drain: {
    key: "drain",
    kind: "drain",
    name: "Floor drain",
    family: "Drain · pipe",
    description: "Removes most pooled liquid and a small amount of residue.",
    activeLabel: "Open drain",
    cost: 1,
    energyCost: 10,
    cooldown: 6,
    accent: "#68a2ad",
  },
  igniter: {
    key: "igniter",
    kind: "igniter",
    name: "Arc igniter",
    family: "Reaction device",
    description: "Burns fuel gas with oxygen. CO₂ weakens or prevents the reaction.",
    activeLabel: "Fire igniter",
    cost: 1,
    energyCost: 7,
    cooldown: 5,
    accent: "#ff874e",
  },
  door: {
    key: "door",
    kind: "door",
    name: "Pressure door",
    family: "Door · actuator",
    description: "Seals the chamber briefly, holding atmosphere and slowing occupants.",
    activeLabel: "Seal room",
    cost: 1,
    energyCost: 10,
    cooldown: 12,
    accent: "#dfc87b",
  },
  boiler: {
    key: "boiler",
    kind: "boiler",
    name: "Flash boiler",
    family: "Reaction device",
    description: "Converts pooled water into hot, pressurized steam.",
    activeLabel: "Flash-boil water",
    cost: 2,
    energyCost: 18,
    cooldown: 8,
    accent: "#d7edf0",
  },
  fan: {
    key: "fan",
    kind: "fan",
    name: "Axial transfer fan",
    family: "Fan · duct",
    description: "Pushes part of this room’s atmosphere into the next chamber.",
    activeLabel: "Push atmosphere",
    cost: 1,
    energyCost: 9,
    cooldown: 5,
    accent: "#76c3b4",
  },
};

export const DEVICE_ORDER: DeviceKey[] = [
  "gas_toxic",
  "gas_co2",
  "gas_fuel",
  "liquid_acid",
  "liquid_caustic",
  "liquid_water",
  "liquid_sludge",
  "vent",
  "drain",
  "igniter",
  "door",
  "boiler",
  "fan",
];

export const STARTING_DEVICES: Partial<Record<RoomId, DeviceKey[]>> = {
  switchyard: ["gas_toxic", "vent", "door"],
  furnace: ["gas_fuel", "igniter", "fan"],
  reservoir: ["liquid_acid", "drain", "liquid_water"],
  gallery: ["gas_co2", "door", "fan"],
  washlock: ["vent", "drain", "boiler", "liquid_water"],
};
