import type { EnemyDefinition, EnemyType, WaveEntry } from "../types";

export const ENEMY_DEFINITIONS: Record<EnemyType, EnemyDefinition> = {
  deckmouth: {
    type: "deckmouth",
    health: 85,
    speed: 0.105,
    coreDamage: 10,
    needsOxygen: true,
    flying: false,
    hazardMultipliers: {
      atmosphere: 1.25,
      corrosion: 1,
      heat: 1,
      pressure: 1,
      radiation: 1,
    },
    color: "#e5c675",
    residueOnDeath: 3,
    matterYield: 5,
    behavior: { kind: "standard" },
    presentation: { appearance: "deckmouth" },
  },
  flintjack: {
    type: "flintjack",
    health: 55,
    speed: 0.185,
    coreDamage: 8,
    needsOxygen: true,
    flying: false,
    hazardMultipliers: {
      atmosphere: 1,
      corrosion: 1,
      heat: 1.1,
      pressure: 0.9,
      radiation: 1,
    },
    color: "#f78f61",
    residueOnDeath: 2,
    matterYield: 5,
    behavior: { kind: "standard" },
    presentation: { appearance: "flintjack" },
  },
  shear_jelly: {
    type: "shear_jelly",
    health: 85,
    speed: 0.145,
    coreDamage: 9,
    needsOxygen: true,
    flying: true,
    hazardMultipliers: {
      atmosphere: 1.15,
      corrosion: 1.05,
      heat: 1.2,
      pressure: 1.5,
      radiation: 1,
    },
    color: "#a07be4",
    residueOnDeath: 2,
    matterYield: 6,
    behavior: { kind: "standard" },
    presentation: { appearance: "shear_jelly" },
  },
  splitback: {
    type: "splitback",
    health: 175,
    speed: 0.075,
    coreDamage: 16,
    needsOxygen: true,
    flying: false,
    hazardMultipliers: {
      atmosphere: 0.42,
      corrosion: 1.55,
      heat: 0.35,
      pressure: 1.15,
      radiation: 1,
    },
    color: "#8dafb2",
    residueOnDeath: 5,
    matterYield: 9,
    behavior: {
      kind: "armored_molt",
      shellHealth: 115,
      exposedSpeedMultiplier: 2.2,
      exposedLocomotionMultipliers: {
        walking: 1,
        climbing: 1.25,
        falling: 1,
        door: 1,
        flying: 1,
      },
    },
    presentation: { appearance: "splitback" },
  },
  redlung: {
    type: "redlung",
    health: 130,
    speed: 0.09,
    coreDamage: 14,
    needsOxygen: true,
    flying: false,
    hazardMultipliers: {
      atmosphere: 0.65,
      corrosion: 1.2,
      heat: 0.55,
      pressure: 1.25,
      radiation: 1,
    },
    color: "#e75667",
    residueOnDeath: 7,
    matterYield: 10,
    behavior: { kind: "standard" },
    presentation: { appearance: "redlung" },
  },
  clatter: {
    type: "clatter",
    health: 75,
    speed: 0.105,
    coreDamage: 10,
    needsOxygen: true,
    flying: false,
    hazardMultipliers: {
      atmosphere: 1.1,
      corrosion: 1,
      heat: 1,
      pressure: 1,
      radiation: 1,
    },
    color: "#a6d66d",
    residueOnDeath: 3,
    matterYield: 6,
    behavior: {
      kind: "ladder_runner",
      locomotionMultipliers: {
        walking: 0.82,
        climbing: 2,
        falling: 1,
        door: 1,
        flying: 1,
      },
    },
    presentation: { appearance: "clatter" },
  },
  anchor: {
    type: "anchor",
    health: 75,
    speed: 0.1,
    coreDamage: 11,
    needsOxygen: true,
    flying: false,
    hazardMultipliers: {
      atmosphere: 1,
      corrosion: 1.15,
      heat: 1,
      pressure: 1,
      radiation: 1,
    },
    color: "#62c9c2",
    residueOnDeath: 3,
    matterYield: 8,
    behavior: {
      kind: "shared_field",
      capacity: 170,
      rechargePerSecond: 15.3,
      activationFraction: 0.25,
    },
    presentation: { appearance: "anchor" },
  },
  glowbag: {
    type: "glowbag",
    health: 75,
    speed: 0.14,
    coreDamage: 10,
    needsOxygen: false,
    flying: true,
    hazardMultipliers: {
      atmosphere: 0.8,
      corrosion: 1.1,
      heat: 1.3,
      pressure: 1.4,
      radiation: 1,
    },
    color: "#e7d45b",
    residueOnDeath: 2,
    matterYield: 7,
    behavior: {
      kind: "gas_emitter",
      species: "hydrogen",
      reservoir: 6,
      emissionRate: 0.6,
    },
    presentation: { appearance: "glowbag" },
  },
};

export const enemySequence = (
  count: number,
  type: EnemyType,
  start: number,
  interval: number,
  levelOffset = 0
): WaveEntry[] =>
  Array.from({ length: count }, (_, index) => ({
    at: start + index * interval,
    type,
    routeId: "entry_to_core",
    levelOffset,
  }));

export const MORROW_POCKET_WAVES: WaveEntry[][] = [
  enemySequence(7, "deckmouth", 0.5, 2.35),
  [
    ...enemySequence(4, "flintjack", 0.5, 1.8),
    ...enemySequence(2, "shear_jelly", 3, 3),
    ...enemySequence(3, "clatter", 2, 2.45, 1),
  ].sort((left, right) => left.at - right.at),
  [
    ...enemySequence(2, "redlung", 0.5, 3.6),
    ...enemySequence(4, "splitback", 2, 2.9, 1),
    ...enemySequence(1, "anchor", 3.5, 1),
  ].sort((left, right) => left.at - right.at),
  [
    ...enemySequence(6, "flintjack", 0.5, 1.55),
    ...enemySequence(4, "splitback", 2, 2.7),
    ...enemySequence(2, "shear_jelly", 4, 3.1),
    ...enemySequence(2, "glowbag", 3, 3.6, 1),
    ...enemySequence(1, "anchor", 4.5, 1),
  ].sort((left, right) => left.at - right.at),
  [
    ...enemySequence(4, "deckmouth", 0.5, 1.8),
    ...enemySequence(4, "splitback", 1.5, 2.45, 1),
    ...enemySequence(3, "redlung", 3, 2.8, 1),
    ...enemySequence(3, "shear_jelly", 4.5, 2.7),
    ...enemySequence(3, "clatter", 2.5, 2.25),
    ...enemySequence(2, "glowbag", 4, 3.6),
    ...enemySequence(1, "anchor", 5, 1),
  ].sort((left, right) => left.at - right.at),
];
