import type { ConnectionDefinition, RoomDefinition, RoomId } from "../types";

export const ROOM_DEFINITIONS: Record<RoomId, RoomDefinition> = {
  west_intake: {
    id: "west_intake",
    name: "West Intake",
    code: "IN-01",
    kind: "spawn",
    position: { x: 84, y: 178 },
    neighbors: ["switchyard"],
    forward: ["switchyard"],
    slots: 0,
    blurb: "Primary breach point. Atmosphere arrives untreated.",
  },
  lower_intake: {
    id: "lower_intake",
    name: "Lower Intake",
    code: "IN-02",
    kind: "spawn",
    position: { x: 94, y: 438 },
    neighbors: ["reservoir"],
    forward: ["reservoir"],
    slots: 0,
    blurb: "Secondary breach point. Opens from cycle two onward.",
  },
  switchyard: {
    id: "switchyard",
    name: "Switchyard",
    code: "CH-11",
    kind: "chamber",
    position: { x: 292, y: 228 },
    neighbors: ["west_intake", "furnace", "reservoir"],
    forward: ["furnace", "reservoir"],
    slots: 5,
    blurb: "A flexible first-contact chamber with a wide duct manifold.",
  },
  furnace: {
    id: "furnace",
    name: "Furnace Hall",
    code: "CH-24",
    kind: "chamber",
    position: { x: 498, y: 143 },
    neighbors: ["switchyard", "gallery"],
    forward: ["gallery"],
    slots: 5,
    blurb: "Dry upper route built to hold a combustible atmosphere.",
  },
  reservoir: {
    id: "reservoir",
    name: "Reservoir",
    code: "CH-32",
    kind: "chamber",
    position: { x: 490, y: 407 },
    neighbors: ["lower_intake", "switchyard", "gallery"],
    forward: ["gallery"],
    slots: 5,
    blurb: "Deep floor basin suited to acids, caustics, and sludge.",
  },
  gallery: {
    id: "gallery",
    name: "Pressure Gallery",
    code: "CH-43",
    kind: "chamber",
    position: { x: 699, y: 269 },
    neighbors: ["furnace", "reservoir", "washlock"],
    forward: ["washlock"],
    slots: 5,
    blurb: "Both paths converge here. Composition mistakes do too.",
  },
  washlock: {
    id: "washlock",
    name: "Washlock",
    code: "CH-51",
    kind: "chamber",
    position: { x: 866, y: 340 },
    neighbors: ["gallery", "core"],
    forward: ["core"],
    slots: 5,
    blurb: "The final service room before the core bulkhead.",
  },
  core: {
    id: "core",
    name: "Catalyst Core",
    code: "CORE",
    kind: "core",
    position: { x: 1037, y: 283 },
    neighbors: ["washlock"],
    forward: [],
    slots: 0,
    blurb: "Keep integrity above zero through five assault cycles.",
  },
};

export const ROOM_ORDER = Object.keys(ROOM_DEFINITIONS) as RoomId[];

export const CONNECTIONS: ConnectionDefinition[] = [
  { from: "west_intake", to: "switchyard" },
  { from: "lower_intake", to: "reservoir" },
  { from: "switchyard", to: "furnace" },
  { from: "switchyard", to: "reservoir" },
  { from: "furnace", to: "gallery" },
  { from: "reservoir", to: "gallery" },
  { from: "gallery", to: "washlock" },
  { from: "washlock", to: "core" },
];
