import type {
  DamageSourceId,
  HazardChannels,
  TowerChassisId,
  TowerDefinition,
  TowerUpgradeDefinition,
  TowerUpgradeId,
} from "../types";

const channels = (values: Partial<HazardChannels>): HazardChannels => ({
  atmosphere: 0,
  corrosion: 0,
  heat: 0,
  pressure: 0,
  radiation: 0,
  ...values,
});

const upgrade = (
  id: TowerUpgradeId,
  cost: number,
  values: Partial<Omit<TowerUpgradeDefinition, "id" | "cost">>
): TowerUpgradeDefinition => ({
  id,
  cost,
  requires: [],
  damageMultiplier: 1,
  cadenceMultiplier: 1,
  rangeDelta: 0,
  targetCapDelta: 0,
  arcDelta: 0,
  supplyMode: "unchanged",
  ...values,
});

const packet = (sourceId: DamageSourceId, values: Partial<HazardChannels>) => ({
  sourceId,
  channels: channels(values),
});

export const TOWER_DEFINITIONS: Record<TowerChassisId, TowerDefinition> = {
  bolt_caster: {
    id: "bolt_caster",
    role: "single_target",
    buildCost: 18,
    recoveryRatio: 0.75,
    footprint: { width: 1, height: 1 },
    mountFaces: ["floor", "left_wall", "right_wall", "ceiling"],
    orientations: ["left", "right", "up", "down"],
    range: 8,
    minimumRange: 0,
    firingArc: 150,
    lineOfSight: "required",
    cadence: 0.8,
    targetCap: 1,
    eligibleLayers: ["ground", "flying"],
    targetPolicies: ["first", "last", "nearest", "strongest", "weakest", "armored"],
    attack: {
      strategy: "hitscan",
      projectileSpeed: 0,
      radius: 0,
      packets: [packet("tower_bolt", { pressure: 24 })],
      controlEffects: [],
    },
    upgrades: [
      upgrade("bolt_calibration", 9, { damageMultiplier: 1.45 }),
      upgrade("bolt_piercing", 12, {
        requires: ["bolt_calibration"],
        damageMultiplier: 1.25,
        rangeDelta: 2,
      }),
    ],
    supply: null,
    color: "#f0c96a",
  },
  repeater: {
    id: "repeater",
    role: "rapid_service",
    buildCost: 16,
    recoveryRatio: 0.7,
    footprint: { width: 1, height: 1 },
    mountFaces: ["floor", "left_wall", "right_wall", "ceiling"],
    orientations: ["left", "right", "up", "down"],
    range: 8,
    minimumRange: 0,
    firingArc: 180,
    lineOfSight: "required",
    cadence: 3.2,
    targetCap: 1,
    eligibleLayers: ["ground", "flying"],
    targetPolicies: ["first", "last", "nearest", "weakest", "flying"],
    attack: {
      strategy: "projectile",
      projectileSpeed: 18,
      radius: 0,
      packets: [packet("tower_repeater", { pressure: 10 })],
      controlEffects: [],
    },
    upgrades: [
      upgrade("repeater_feed", 8, { cadenceMultiplier: 1.45 }),
      upgrade("repeater_tracking", 11, {
        requires: ["repeater_feed"],
        targetCapDelta: 1,
        rangeDelta: 1,
      }),
    ],
    supply: null,
    color: "#e88a52",
  },
  line_projector: {
    id: "line_projector",
    role: "area",
    buildCost: 25,
    recoveryRatio: 0.7,
    footprint: { width: 1, height: 1 },
    mountFaces: ["left_wall", "right_wall", "ceiling"],
    orientations: ["left", "right", "down"],
    range: 8,
    minimumRange: 0,
    firingArc: 70,
    lineOfSight: "fixed_projection",
    cadence: 0.7,
    targetCap: 4,
    eligibleLayers: ["ground", "flying"],
    targetPolicies: ["first", "last", "nearest"],
    attack: {
      strategy: "cone",
      projectileSpeed: 0,
      radius: 2.4,
      packets: [packet("tower_projector", { heat: 22 })],
      controlEffects: [],
    },
    upgrades: [
      upgrade("projector_focus", 13, { damageMultiplier: 1.4, rangeDelta: 1.5 }),
      upgrade("projector_fan", 14, {
        requires: ["projector_focus"],
        targetCapDelta: 2,
        arcDelta: 24,
      }),
    ],
    supply: {
      port: "gas",
      acceptedSpecies: ["hydrogen"],
      rate: 0.35,
      localCapacity: 8,
      insufficientFlow: "direct_mode",
    },
    color: "#ff6b48",
  },
  mortar: {
    id: "mortar",
    role: "area",
    buildCost: 30,
    recoveryRatio: 0.7,
    footprint: { width: 2, height: 1 },
    mountFaces: ["floor"],
    orientations: ["left", "right"],
    range: 11,
    minimumRange: 2.5,
    firingArc: 170,
    lineOfSight: "lobbed",
    cadence: 0.45,
    targetCap: 5,
    eligibleLayers: ["ground"],
    targetPolicies: ["first", "last", "strongest", "armored", "support"],
    attack: {
      strategy: "lob",
      projectileSpeed: 9,
      radius: 2.2,
      packets: [packet("tower_mortar", { pressure: 34, heat: 8 })],
      controlEffects: [],
    },
    upgrades: [
      upgrade("mortar_payload", 15, { damageMultiplier: 1.5 }),
      upgrade("mortar_radius", 16, {
        requires: ["mortar_payload"],
        targetCapDelta: 3,
        rangeDelta: 2,
      }),
    ],
    supply: null,
    color: "#91a56c",
  },
  snare_emitter: {
    id: "snare_emitter",
    role: "control",
    buildCost: 22,
    recoveryRatio: 0.75,
    footprint: { width: 1, height: 1 },
    mountFaces: ["floor", "ceiling"],
    orientations: ["left", "right", "down"],
    range: 6,
    minimumRange: 0,
    firingArc: 210,
    lineOfSight: "required",
    cadence: 0.65,
    targetCap: 3,
    eligibleLayers: ["ground"],
    targetPolicies: ["first", "last", "nearest", "strongest"],
    attack: {
      strategy: "area",
      projectileSpeed: 0,
      radius: 1.8,
      packets: [packet("tower_snare", { radiation: 2 })],
      controlEffects: [
        {
          kind: "slow",
          magnitude: 0.38,
          duration: 2.8,
          stacking: "strongest",
          refresh: "replace",
          floor: 0.35,
        },
      ],
    },
    upgrades: [
      upgrade("snare_duration", 11, { cadenceMultiplier: 1.2 }),
      upgrade("snare_field", 13, {
        requires: ["snare_duration"],
        targetCapDelta: 2,
        rangeDelta: 1,
      }),
    ],
    supply: null,
    color: "#65c9b5",
  },
  flak_nest: {
    id: "flak_nest",
    role: "upper",
    buildCost: 24,
    recoveryRatio: 0.72,
    footprint: { width: 1, height: 1 },
    mountFaces: ["floor", "left_wall", "right_wall", "ceiling"],
    orientations: ["left", "right", "up", "down"],
    range: 9,
    minimumRange: 1,
    firingArc: 190,
    lineOfSight: "required",
    cadence: 1.4,
    targetCap: 2,
    eligibleLayers: ["flying"],
    targetPolicies: ["first", "last", "nearest", "flying", "support"],
    attack: {
      strategy: "projectile",
      projectileSpeed: 15,
      radius: 1.2,
      packets: [packet("tower_flak", { pressure: 17 })],
      controlEffects: [],
    },
    upgrades: [
      upgrade("flak_burst", 12, { cadenceMultiplier: 1.3, targetCapDelta: 1 }),
      upgrade("flak_ceiling", 14, {
        requires: ["flak_burst"],
        damageMultiplier: 1.35,
        rangeDelta: 2,
      }),
    ],
    supply: null,
    color: "#a886dc",
  },
  relay: {
    id: "relay",
    role: "support",
    buildCost: 28,
    recoveryRatio: 0.8,
    footprint: { width: 1, height: 1 },
    mountFaces: ["floor", "left_wall", "right_wall", "ceiling"],
    orientations: ["left", "right", "up", "down"],
    range: 7,
    minimumRange: 0,
    firingArc: 360,
    lineOfSight: "required",
    cadence: 0.5,
    targetCap: 1,
    eligibleLayers: ["ground", "flying"],
    targetPolicies: ["support", "first", "nearest"],
    attack: {
      strategy: "hitscan",
      projectileSpeed: 0,
      radius: 0,
      packets: [packet("tower_relay", { radiation: 8 })],
      controlEffects: [
        {
          kind: "reveal",
          magnitude: 1,
          duration: 4,
          stacking: "strongest",
          refresh: "replace",
          floor: 0,
        },
        {
          kind: "armor_break",
          magnitude: 0.18,
          duration: 4,
          stacking: "additive",
          refresh: "extend",
          floor: 0.45,
        },
      ],
    },
    upgrades: [
      upgrade("relay_range", 14, { rangeDelta: 2 }),
      upgrade("relay_service", 16, {
        requires: ["relay_range"],
        cadenceMultiplier: 1.4,
        targetCapDelta: 1,
      }),
    ],
    supply: null,
    color: "#72d7e3",
  },
};
