import type { SpeciesDefinition, SpeciesId } from "../../types";
import { GAS_COLORS, GAS_LABELS } from "../substancePresentation";

export const ADVANCED_GAS_DEFINITIONS = {
  methane: {
    id: "methane",
    formula: GAS_LABELS.methane,
    phase: "gas",
    elements: { C: 1, H: 4 },
    molarMass: 16.043,
    referenceDensity: 0.554,
    color: GAS_COLORS.methane,
    damageSourceId: null,
    hazards: [],
  },
  ammonia: {
    id: "ammonia",
    formula: GAS_LABELS.ammonia,
    phase: "gas",
    elements: { N: 1, H: 3 },
    molarMass: 17.031,
    referenceDensity: 0.588,
    color: GAS_COLORS.ammonia,
    damageSourceId: "nitrogen_chemistry",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.008,
        rate: 367.41,
        channel: "atmosphere",
        exposure: "all",
      },
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.018,
        rate: 138.8,
        channel: "corrosion",
        exposure: "all",
      },
    ],
  },
  nitric_oxide: {
    id: "nitric_oxide",
    formula: GAS_LABELS.nitric_oxide,
    phase: "gas",
    elements: { N: 1, O: 1 },
    molarMass: 30.006,
    referenceDensity: 1.036,
    color: GAS_COLORS.nitric_oxide,
    damageSourceId: "nitrogen_chemistry",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.006,
        rate: 440.9,
        channel: "atmosphere",
        exposure: "all",
      },
    ],
  },
  nitrogen_dioxide: {
    id: "nitrogen_dioxide",
    formula: GAS_LABELS.nitrogen_dioxide,
    phase: "gas",
    elements: { N: 1, O: 2 },
    molarMass: 46.005,
    referenceDensity: 1.588,
    color: GAS_COLORS.nitrogen_dioxide,
    damageSourceId: "nitrogen_chemistry",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.003,
        rate: 808.31,
        channel: "atmosphere",
        exposure: "all",
      },
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.006,
        rate: 318.43,
        channel: "corrosion",
        exposure: "all",
      },
    ],
  },
  nitrous_oxide: {
    id: "nitrous_oxide",
    formula: GAS_LABELS.nitrous_oxide,
    phase: "gas",
    elements: { N: 2, O: 1 },
    molarMass: 44.013,
    referenceDensity: 1.519,
    color: GAS_COLORS.nitrous_oxide,
    damageSourceId: null,
    hazards: [],
  },
  nickel_carbonyl: {
    id: "nickel_carbonyl",
    formula: GAS_LABELS.nickel_carbonyl,
    phase: "gas",
    elements: { Ni: 1, C: 4, O: 4 },
    molarMass: 170.73,
    referenceDensity: 5.89,
    color: GAS_COLORS.nickel_carbonyl,
    damageSourceId: "nickel_carbonyl",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.000_01,
        rate: 9_201.69,
        channel: "atmosphere",
        exposure: "all",
      },
    ],
  },
  uranium_hexafluoride: {
    id: "uranium_hexafluoride",
    formula: GAS_LABELS.uranium_hexafluoride,
    phase: "gas",
    elements: { U: 1, F: 6 },
    molarMass: 352.02,
    referenceDensity: 12.1,
    color: GAS_COLORS.uranium_hexafluoride,
    damageSourceId: "uranium_chemistry",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.000_2,
        rate: 412.07,
        channel: "atmosphere",
        exposure: "all",
      },
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0,
        rate: 0.1177,
        channel: "radiation",
        exposure: "all",
      },
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.000_4,
        rate: 186.41,
        channel: "corrosion",
        exposure: "all",
      },
    ],
  },
  hydrogen_fluoride: {
    id: "hydrogen_fluoride",
    formula: GAS_LABELS.hydrogen_fluoride,
    phase: "gas",
    elements: { H: 1, F: 1 },
    molarMass: 20.006,
    referenceDensity: 0.69,
    color: GAS_COLORS.hydrogen_fluoride,
    damageSourceId: "hydrogen_fluoride",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.002,
        rate: 258.74,
        channel: "atmosphere",
        exposure: "all",
      },
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.002,
        rate: 308.5,
        channel: "corrosion",
        exposure: "all",
      },
    ],
  },
  fluorine: {
    id: "fluorine",
    formula: GAS_LABELS.fluorine,
    phase: "gas",
    elements: { F: 2 },
    molarMass: 37.997,
    referenceDensity: 1.312,
    color: GAS_COLORS.fluorine,
    damageSourceId: "fluorine",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.001,
        rate: 320.63,
        channel: "atmosphere",
        exposure: "all",
      },
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.001,
        rate: 408.07,
        channel: "corrosion",
        exposure: "all",
      },
    ],
  },
} satisfies Partial<Record<SpeciesId, SpeciesDefinition>>;
