import type { SpeciesDefinition, SpeciesId } from "../../types";
import { GAS_COLORS, GAS_LABELS } from "../substancePresentation";

export const BASE_GAS_DEFINITIONS = {
  oxygen: {
    id: "oxygen",
    family: "common",
    formula: GAS_LABELS.oxygen,
    phase: "gas",
    elements: { O: 2 },
    molarMass: 31.998,
    referenceDensity: 1.105,
    color: GAS_COLORS.oxygen,
    damageSourceId: "asphyxiation",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "below",
        threshold: 0.13,
        maximumExcess: null,
        rate: 72.5,
        channel: "atmosphere",
        exposure: "oxygen_breathers",
      },
    ],
  },
  nitrogen: {
    id: "nitrogen",
    family: "common",
    formula: GAS_LABELS.nitrogen,
    phase: "gas",
    elements: { N: 2 },
    molarMass: 28.014,
    referenceDensity: 0.967,
    color: GAS_COLORS.nitrogen,
    damageSourceId: null,
    hazards: [],
  },
  carbon_dioxide: {
    id: "carbon_dioxide",
    family: "carbon_steam",
    formula: GAS_LABELS.carbon_dioxide,
    phase: "gas",
    elements: { C: 1, O: 2 },
    molarMass: 44.01,
    referenceDensity: 1.519,
    color: GAS_COLORS.carbon_dioxide,
    damageSourceId: "asphyxiation",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.14,
        maximumExcess: null,
        rate: 30,
        channel: "atmosphere",
        exposure: "oxygen_breathers",
      },
    ],
  },
  carbon_monoxide: {
    id: "carbon_monoxide",
    family: "carbon_steam",
    formula: GAS_LABELS.carbon_monoxide,
    phase: "gas",
    elements: { C: 1, O: 1 },
    molarMass: 28.01,
    referenceDensity: 0.967,
    color: GAS_COLORS.carbon_monoxide,
    damageSourceId: "carbon_monoxide",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.012,
        maximumExcess: null,
        rate: 84.12,
        channel: "atmosphere",
        exposure: "oxygen_breathers",
      },
    ],
  },
  chlorine: {
    id: "chlorine",
    family: "chlorine_sodium",
    formula: GAS_LABELS.chlorine,
    phase: "gas",
    elements: { Cl: 2 },
    molarMass: 70.9,
    referenceDensity: 2.447,
    color: GAS_COLORS.chlorine,
    damageSourceId: "chlorine_gas",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.004,
        maximumExcess: 0.008,
        rate: 1482.94,
        channel: "atmosphere",
        exposure: "all",
      },
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.004,
        maximumExcess: 0.008,
        rate: 1128.98,
        channel: "corrosion",
        exposure: "all",
      },
    ],
  },
  hydrogen: {
    id: "hydrogen",
    family: "common",
    formula: GAS_LABELS.hydrogen,
    phase: "gas",
    elements: { H: 2 },
    molarMass: 2.016,
    referenceDensity: 0.07,
    color: GAS_COLORS.hydrogen,
    damageSourceId: null,
    hazards: [],
  },
  hydrogen_chloride: {
    id: "hydrogen_chloride",
    family: "chlorine_sodium",
    formula: GAS_LABELS.hydrogen_chloride,
    phase: "gas",
    elements: { H: 1, Cl: 1 },
    molarMass: 36.46,
    referenceDensity: 1.259,
    color: GAS_COLORS.hydrogen_chloride,
    damageSourceId: "hydrogen_chloride_gas",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.006,
        maximumExcess: null,
        rate: 972.58,
        channel: "atmosphere",
        exposure: "all",
      },
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.006,
        maximumExcess: null,
        rate: 1731.16,
        channel: "corrosion",
        exposure: "all",
      },
    ],
  },
  steam: {
    id: "steam",
    family: "common",
    formula: GAS_LABELS.steam,
    phase: "gas",
    elements: { H: 2, O: 1 },
    molarMass: 18.015,
    referenceDensity: 0.622,
    color: GAS_COLORS.steam,
    damageSourceId: "thermal_exposure",
    hazards: [
      {
        basis: "gas_partial_ratio",
        direction: "above",
        threshold: 0.35,
        maximumExcess: null,
        rate: 7.3,
        channel: "heat",
        exposure: "all",
      },
    ],
  },
} satisfies Partial<Record<SpeciesId, SpeciesDefinition>>;
