import type { SpeciesDefinition, SpeciesId } from "../../types";
import { LIQUID_COLORS, LIQUID_LABELS } from "../substancePresentation";

export const LIQUID_DEFINITIONS = {
  water: {
    id: "water",
    formula: LIQUID_LABELS.water,
    phase: "liquid",
    elements: { H: 2, O: 1 },
    molarMass: 18.015,
    referenceDensity: 1,
    color: LIQUID_COLORS.water,
    damageSourceId: null,
    hazards: [],
  },
  sodium_chloride: {
    id: "sodium_chloride",
    formula: LIQUID_LABELS.sodium_chloride,
    phase: "liquid",
    elements: { Na: 1, Cl: 1 },
    molarMass: 58.44,
    referenceDensity: 1.15,
    color: LIQUID_COLORS.sodium_chloride,
    damageSourceId: null,
    hazards: [],
  },
  sodium_hydroxide: {
    id: "sodium_hydroxide",
    formula: LIQUID_LABELS.sodium_hydroxide,
    phase: "liquid",
    elements: { Na: 1, O: 1, H: 1 },
    molarMass: 40,
    referenceDensity: 1.2,
    color: LIQUID_COLORS.sodium_hydroxide,
    damageSourceId: "liquid_corrosion",
    hazards: [
      {
        basis: "liquid_strength",
        direction: "above",
        threshold: 2,
        rate: 20.49,
        channel: "corrosion",
        exposure: "floor_contact",
      },
    ],
  },
  sodium_hypochlorite: {
    id: "sodium_hypochlorite",
    formula: LIQUID_LABELS.sodium_hypochlorite,
    phase: "liquid",
    elements: { Na: 1, O: 1, Cl: 1 },
    molarMass: 74.44,
    referenceDensity: 1.1,
    color: LIQUID_COLORS.sodium_hypochlorite,
    damageSourceId: "liquid_corrosion",
    hazards: [
      {
        basis: "liquid_strength",
        direction: "above",
        threshold: 5,
        rate: 6.902,
        channel: "corrosion",
        exposure: "floor_contact",
      },
    ],
  },
  hydrochloric_acid: {
    id: "hydrochloric_acid",
    formula: LIQUID_LABELS.hydrochloric_acid,
    phase: "liquid",
    elements: { H: 1, Cl: 1 },
    molarMass: 36.46,
    referenceDensity: 1.12,
    color: LIQUID_COLORS.hydrochloric_acid,
    damageSourceId: "liquid_corrosion",
    hazards: [
      {
        basis: "liquid_strength",
        direction: "above",
        threshold: 2,
        rate: 16.38,
        channel: "corrosion",
        exposure: "floor_contact",
      },
    ],
  },
  nitric_acid: {
    id: "nitric_acid",
    formula: LIQUID_LABELS.nitric_acid,
    phase: "liquid",
    elements: { H: 1, N: 1, O: 3 },
    molarMass: 63.012,
    referenceDensity: 1.35,
    color: LIQUID_COLORS.nitric_acid,
    damageSourceId: "nitrogen_chemistry",
    hazards: [
      {
        basis: "liquid_strength",
        direction: "above",
        threshold: 1.5,
        rate: 31.85,
        channel: "corrosion",
        exposure: "floor_contact",
      },
    ],
  },
} satisfies Partial<Record<SpeciesId, SpeciesDefinition>>;
