import type { SpeciesDefinition, SpeciesId } from "../../types";
import { STATIONARY_COLORS, STATIONARY_LABELS } from "../substancePresentation";

export const STATIONARY_DEFINITIONS = {
  solid_carbon: {
    id: "solid_carbon",
    formula: STATIONARY_LABELS.solid_carbon,
    phase: "stationary",
    elements: { C: 1 },
    molarMass: 12.011,
    referenceDensity: 2.1,
    color: STATIONARY_COLORS.solid_carbon,
    damageSourceId: null,
    hazards: [],
  },
  hematite: {
    id: "hematite",
    formula: STATIONARY_LABELS.hematite,
    phase: "stationary",
    elements: { Fe: 2, O: 3 },
    molarMass: 159.687,
    referenceDensity: 5.26,
    color: STATIONARY_COLORS.hematite,
    damageSourceId: null,
    hazards: [],
  },
  magnetite: {
    id: "magnetite",
    formula: STATIONARY_LABELS.magnetite,
    phase: "stationary",
    elements: { Fe: 3, O: 4 },
    molarMass: 231.531,
    referenceDensity: 5.18,
    color: STATIONARY_COLORS.magnetite,
    damageSourceId: null,
    hazards: [],
  },
  nickel_oxide: {
    id: "nickel_oxide",
    formula: STATIONARY_LABELS.nickel_oxide,
    phase: "stationary",
    elements: { Ni: 1, O: 1 },
    molarMass: 74.692,
    referenceDensity: 6.67,
    color: STATIONARY_COLORS.nickel_oxide,
    damageSourceId: null,
    hazards: [],
  },
  surface_nickel: {
    id: "surface_nickel",
    formula: STATIONARY_LABELS.surface_nickel,
    phase: "stationary",
    elements: { Ni: 1 },
    molarMass: 58.693,
    referenceDensity: 8.91,
    color: STATIONARY_COLORS.surface_nickel,
    damageSourceId: null,
    hazards: [],
  },
  uranyl_fluoride: {
    id: "uranyl_fluoride",
    formula: STATIONARY_LABELS.uranyl_fluoride,
    phase: "stationary",
    elements: { U: 1, O: 2, F: 2 },
    molarMass: 308.02,
    referenceDensity: 6.4,
    color: STATIONARY_COLORS.uranyl_fluoride,
    damageSourceId: "uranium_chemistry",
    hazards: [
      {
        basis: "stationary_inventory",
        direction: "above",
        threshold: 0,
        rate: 0.02453,
        channel: "radiation",
        exposure: "all",
      },
    ],
  },
  iron_catalyst: {
    id: "iron_catalyst",
    formula: STATIONARY_LABELS.iron_catalyst,
    phase: "stationary",
    elements: { Fe: 1 },
    molarMass: 55.845,
    referenceDensity: 7.87,
    color: STATIONARY_COLORS.iron_catalyst,
    damageSourceId: null,
    hazards: [],
  },
  platinum_catalyst: {
    id: "platinum_catalyst",
    formula: STATIONARY_LABELS.platinum_catalyst,
    phase: "stationary",
    elements: { Pt: 1 },
    molarMass: 195.084,
    referenceDensity: 21.45,
    color: STATIONARY_COLORS.platinum_catalyst,
    damageSourceId: null,
    hazards: [],
  },
} satisfies Partial<Record<SpeciesId, SpeciesDefinition>>;
