import type { ReactionDefinition, ReactionId } from "../../types";

export const NITROGEN_OXIDE_REACTIONS = {
  ammonia_synthesis: {
    id: "ammonia_synthesis",
    code: "NO-1",
    kind: "chemical",
    equation: "N₂(g) + 3 H₂(g) ⇌ 2 NH₃(g) + heat",
    reactants: [
      { species: "nitrogen", coefficient: 1 },
      { species: "hydrogen", coefficient: 3 },
    ],
    products: [{ species: "ammonia", coefficient: 2 }],
    behavior: {
      kind: "mass_action",
      maximumRate: 0.62,
      halfSaturation: 3,
      contact: "gas",
      forward: {
        rateConstant: 1,
        rateOrders: [
          { species: "nitrogen", order: 1 },
          { species: "hydrogen", order: 2 },
        ],
        activationTemperature: 78,
        fullActivationTemperature: 125,
        minimumPressureRatio: 1.4,
        fullPressureRatio: 3.2,
      },
      reverse: {
        rateConstant: 0.3,
        rateOrders: [{ species: "ammonia", order: 2 }],
        activationTemperature: 145,
        fullActivationTemperature: 205,
      },
      catalyst: { species: "iron_catalyst", halfSaturation: 1 },
      gasHeatPerExtent: 2.6,
      roomHeatPerExtent: 0.56,
    },
  },
  ammonia_oxidation: {
    id: "ammonia_oxidation",
    code: "NO-2",
    kind: "chemical",
    equation: "4 NH₃(g) + 5 O₂(g) → 4 NO(g) + 6 H₂O(g) + heat",
    reactants: [
      { species: "ammonia", coefficient: 4 },
      { species: "oxygen", coefficient: 5 },
    ],
    products: [
      { species: "nitric_oxide", coefficient: 4 },
      { species: "steam", coefficient: 6 },
    ],
    behavior: {
      kind: "mass_action",
      maximumRate: 0.42,
      halfSaturation: 3,
      contact: "gas",
      forward: {
        rateConstant: 1,
        rateOrders: [
          { species: "ammonia", order: 1 },
          { species: "oxygen", order: 1 },
        ],
        activationTemperature: 88,
        fullActivationTemperature: 135,
        deactivationTemperature: 205,
        inactiveTemperature: 250,
      },
      catalyst: { species: "platinum_catalyst", halfSaturation: 0.65 },
      gasHeatPerExtent: 4.8,
      roomHeatPerExtent: 1.05,
    },
  },
  nitric_oxide_oxidation: {
    id: "nitric_oxide_oxidation",
    code: "NO-3",
    kind: "chemical",
    equation: "2 NO(g) + O₂(g) → 2 NO₂(g) + heat",
    reactants: [
      { species: "nitric_oxide", coefficient: 2 },
      { species: "oxygen", coefficient: 1 },
    ],
    products: [{ species: "nitrogen_dioxide", coefficient: 2 }],
    behavior: {
      kind: "mass_action",
      maximumRate: 0.7,
      halfSaturation: 2,
      contact: "gas",
      forward: {
        rateConstant: 1,
        rateOrders: [
          { species: "nitric_oxide", order: 2 },
          { species: "oxygen", order: 1 },
        ],
        activationTemperature: -20,
        fullActivationTemperature: 15,
        deactivationTemperature: 95,
        inactiveTemperature: 160,
      },
      gasHeatPerExtent: 1.2,
      roomHeatPerExtent: 0.2,
    },
  },
  nitrogen_dioxide_absorption: {
    id: "nitrogen_dioxide_absorption",
    code: "NO-4",
    kind: "chemical",
    equation: "3 NO₂(g) + H₂O(l) → 2 HNO₃(aq) + NO(g) + heat",
    reactants: [
      { species: "nitrogen_dioxide", coefficient: 3 },
      { species: "water", coefficient: 1 },
    ],
    products: [
      { species: "nitric_acid", coefficient: 2 },
      { species: "nitric_oxide", coefficient: 1 },
    ],
    behavior: {
      kind: "mass_action",
      maximumRate: 0.75,
      halfSaturation: 2,
      contact: "liquid",
      forward: {
        rateConstant: 1,
        rateOrders: [
          { species: "nitrogen_dioxide", order: 1 },
          { species: "water", order: 1 },
        ],
        activationTemperature: 0,
        fullActivationTemperature: 20,
        deactivationTemperature: 72,
        inactiveTemperature: 110,
      },
      gasHeatPerExtent: 0.4,
      roomHeatPerExtent: 0.38,
    },
  },
  nox_ammonia_reduction: {
    id: "nox_ammonia_reduction",
    code: "NO-5",
    kind: "chemical",
    equation: "4 NH₃(g) + 4 NO(g) + O₂(g) → 4 N₂(g) + 6 H₂O(g)",
    reactants: [
      { species: "ammonia", coefficient: 4 },
      { species: "nitric_oxide", coefficient: 4 },
      { species: "oxygen", coefficient: 1 },
    ],
    products: [
      { species: "nitrogen", coefficient: 4 },
      { species: "steam", coefficient: 6 },
    ],
    behavior: {
      kind: "mass_action",
      maximumRate: 0.44,
      halfSaturation: 2.8,
      contact: "gas",
      forward: {
        rateConstant: 1,
        rateOrders: [
          { species: "ammonia", order: 1 },
          { species: "nitric_oxide", order: 1 },
        ],
        activationTemperature: 82,
        fullActivationTemperature: 125,
        deactivationTemperature: 185,
        inactiveTemperature: 230,
      },
      catalyst: { species: "platinum_catalyst", halfSaturation: 0.65 },
      gasHeatPerExtent: 3.2,
      roomHeatPerExtent: 0.7,
    },
  },
  nitrous_oxide_side_path: {
    id: "nitrous_oxide_side_path",
    code: "NO-6",
    kind: "chemical",
    equation: "2 NH₃(g) + 2 O₂(g) → N₂O(g) + 3 H₂O(g)",
    reactants: [
      { species: "ammonia", coefficient: 2 },
      { species: "oxygen", coefficient: 2 },
    ],
    products: [
      { species: "nitrous_oxide", coefficient: 1 },
      { species: "steam", coefficient: 3 },
    ],
    behavior: {
      kind: "mass_action",
      maximumRate: 0.22,
      halfSaturation: 2.4,
      contact: "gas",
      forward: {
        rateConstant: 1,
        rateOrders: [
          { species: "ammonia", order: 1 },
          { species: "oxygen", order: 1 },
        ],
        activationTemperature: 52,
        fullActivationTemperature: 88,
        deactivationTemperature: 128,
        inactiveTemperature: 180,
      },
      catalyst: { species: "platinum_catalyst", halfSaturation: 0.65 },
      gasHeatPerExtent: 2.2,
      roomHeatPerExtent: 0.48,
    },
  },
} satisfies Partial<Record<ReactionId, ReactionDefinition>>;
